document.writeln("<div class=\'container header\'>");
document.writeln("		<div class=\'title\'>");
document.writeln("			<div class=\'logo\'>");
document.writeln("				<img src=\'scdtjx/img/home/logo.png\' alt=\'\'>");
document.writeln("			</div>");
document.writeln("			<div class=\'tel\'>");
document.writeln("			<div class=\'tel-box\'>");
document.writeln("				<p class=\'rx\'>热线电话：</p>");
document.writeln("				<p class=\'hm\'><span class=\'glyphicon glyphicon-earphone\'></span>18398910491</p>");
document.writeln("			</div>");
document.writeln("			</div>		");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<div class=\'navbar-wrapper\'>");
document.writeln("	    <div class=\'container-fluid\'>");
document.writeln("	      <nav class=\'navbar navbar-inverse\'>");
document.writeln("	        <div class=\'container\'>");
document.writeln("	          <div class=\'navbar-header\'>");
document.writeln("	            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#navbar\' aria-expanded=\'false\' aria-controls=\'navbar\'>");
document.writeln("	              <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("	              <span class=\'icon-bar\'></span>");
document.writeln("	              <span class=\'icon-bar\'></span>");
document.writeln("	              <span class=\'icon-bar\'></span>");
document.writeln("	            </button>");
document.writeln("	            <a class=\'navbar-brand\' href=\'index.do\'>首页</a>");
document.writeln("	          </div>");
document.writeln("");
document.writeln("	          <div id=\'navbar\' class=\'navbar-collapse collapse\'>");
document.writeln("	            <ul class=\'nav navbar-nav\' id=\'nav\'>");
document.writeln("	              <li><a class=\'nav-product\' href=\'product.do\' class=\'sy\'>产品展示</a></li>");
document.writeln("	              <li><a class=\'nav-undertake\' href=\'underTake.do\'>工程承接</a></li>");
document.writeln("	              <li><a class=\'nav-news\' href=\'news.do\'>新闻动态</a></li>");
document.writeln("	              <li><a class=\'nav-about\' href=\'scdtjx/about.jsp\'>公司介绍</a></li>");
document.writeln("	              <li><a class=\'nav-contact\' href=\'scdtjx/contact.jsp\'>联系我们</a></li>");
document.writeln("	            </ul>");
document.writeln("	          </div>");
document.writeln("	        </div>");
document.writeln("	      </nav>");
document.writeln("	    </div>");
document.writeln("	</div>");